name: autofix.ci

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  fix:
    name: Fix
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'renovate[bot]' && ! contains(github.event.head_commit.author.name , 'renovate[bot]') && ! contains(github.event.head_commit.message , 'chore(release)') && ! contains(github.event.head_commit.message , '[autofix.ci]') }}
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          fetch-depth: 0
          filter: tree:0
      - name: Setup toolchains
        uses: jdx/mise-action@9dc7d5dd454262207dea3ab5a06a3df6afc8ff26 # v3.4.1
      - name: Setup Socket Firewall
        uses: SocketDev/action@4337a545deecc20f19a909e52db7a2f6ba292f42 # v1.2.0
        with:
          mode: firewall
      - name: Update package lock file
        run: |
          rm -rf **/node_modules pnpm-lock.yaml
          pnpm install --no-frozen-lockfile
      - name: Optimize dependencies with @socketregistry overrides
        run: socket optimize
      - name: Fix dependencies audit
        run: pnpm audit --fix
      - name: Set SHAs
        uses: nrwl/nx-set-shas@3e9ad7370203c1e93d109be57f3b72eb0eb511b1 # v4.4.0
      - name: Fix
        run: pnpm nx affected -t fix
        env:
          NX_KEY: ${{ secrets.NX_KEY }}
          AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Submit autofix
        uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27 # v1.3.2
  lint:
    name: Lint and Build
    runs-on: ubuntu-latest
    needs: fix
    if: ${{ ! contains(github.event.head_commit.message , 'chore(release)') && (always() && (needs.fix.result == 'success' || needs.fix.result == 'skipped')) }}
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          fetch-depth: 0
          filter: tree:0
      - name: Setup toolchains
        uses: jdx/mise-action@9dc7d5dd454262207dea3ab5a06a3df6afc8ff26 # v3.4.1
      - name: Setup Socket Firewall
        uses: SocketDev/action@4337a545deecc20f19a909e52db7a2f6ba292f42 # v1.2.0
        with:
          mode: firewall
      - name: Install dependencies
        run: sfw pnpm install
      - name: Set SHAs
        uses: nrwl/nx-set-shas@3e9ad7370203c1e93d109be57f3b72eb0eb511b1 # v4.4.0
      - name: Check
        run: pnpm nx affected -t check
        env:
          NX_KEY: ${{ secrets.NX_KEY }}
          AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
