name: autofix.ci

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  fix:
    name: Fix
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'renovate[bot]' && ! contains(github.event.head_commit.author.name , 'renovate[bot]') && ! contains(github.event.head_commit.message , 'chore(release)') }}
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          filter: tree:0
      - name: Setup toolchains
        uses: jdx/mise-action@9dc7d5dd454262207dea3ab5a06a3df6afc8ff26 # v3.4.1
      - name: Setup Socket Firewall
        uses: SocketDev/action@4337a545deecc20f19a909e52db7a2f6ba292f42 # v1.2.0
        with:
          mode: firewall
      - name: Install dependencies
        run: sfw pnpm install --no-frozen-lockfile
      - name: Set SHAs
        uses: nrwl/nx-set-shas@826660b82addbef3abff5fa871492ebad618c9e1 # v4.3.3
      - name: Optimize packages
        run: socket optimize
      - name: Update package lock file
        run: |
          rm -rf **/node_modules pnpm-lock.yaml
          pnpm install --no-frozen-lockfile
      - name: Fix
        run: pnpm nx affected -t fix
        env:
          NX_KEY: ${{ secrets.NX_KEY }}
          AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Submit autofix
        uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27 # v1.3.2
  lint:
    name: Lint and Build
    runs-on: ubuntu-latest
    needs: fix
    if: ${{ ! contains(github.event.head_commit.message , 'chore(release)') && (always() && (needs.fix.result == 'success' || needs.fix.result == 'skipped')) }}
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          filter: tree:0
      - name: Setup toolchains
        uses: jdx/mise-action@9dc7d5dd454262207dea3ab5a06a3df6afc8ff26 # v3.4.1
      - name: Setup Socket Firewall
        uses: SocketDev/action@4337a545deecc20f19a909e52db7a2f6ba292f42 # v1.2.0
        with:
          mode: firewall
      - name: Install dependencies
        run: sfw pnpm install
      - name: Set SHAs
        uses: nrwl/nx-set-shas@826660b82addbef3abff5fa871492ebad618c9e1 # v4.3.3
      - name: Check
        run: pnpm nx affected -t check
        env:
          NX_KEY: ${{ secrets.NX_KEY }}
          AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
